-- Tenant-scope user identity.
--
-- Before this migration, `users.staffbase_user_id` was globally unique — one
-- row per staffbase user across the whole deployment. With multi-tenant
-- support, the SAME human email may exist as a different user object in two
-- different Staffbase workspaces, and we want to model them as two distinct
-- accounts (separate conversation history, separate OAuth connections, etc).
--
-- Schema after:
--   users.staffbase_branch_id (not null, fk to staffbase_tenants)
--   unique (staffbase_branch_id, staffbase_user_id)
--   (staffbase_user_id alone is NOT unique anymore)
--
-- Note: we intentionally do NOT enforce unique(branch_id, email). Existing
-- data has duplicate emails per tenant (re-onboardings, alias addresses,
-- bot accounts), and staffbase_user_id is the canonical identity anyway.
--
-- connections is left structurally unchanged: its `unique (user_id, provider)`
-- is already tenant-scoped via the now-tenant-scoped `users.id` row.
--
-- Backfill: every existing user gets stamped with the first registered
-- tenant. Single-tenant deployments are unaffected. Multi-tenant deployments
-- effectively "anchor" all legacy users to the first tenant; users who exist
-- in additional tenants will be created on first sign-in to that tenant.

alter table users
  add column if not exists staffbase_branch_id text;

do $$
declare
  default_branch text;
begin
  if exists (select 1 from information_schema.tables where table_name = 'staffbase_tenants') then
    select branch_id into default_branch
      from staffbase_tenants
      order by created_at asc
      limit 1;
    if default_branch is not null then
      update users
        set staffbase_branch_id = default_branch
        where staffbase_branch_id is null;
    end if;
  end if;
end $$;

-- Drop the global staffbase_user_id uniqueness so the same Staffbase user
-- ID can exist in two tenants (each tenant has an independent directory, so
-- IDs are workspace-scoped). The constraint name is auto-generated by
-- Postgres for `unique not null` on a single column — handle both common
-- forms.
do $$
begin
  if exists (select 1 from pg_constraint where conname = 'users_staffbase_user_id_key') then
    alter table users drop constraint users_staffbase_user_id_key;
  end if;
end $$;

create unique index if not exists users_branch_staffbase_user_id_key
  on users (staffbase_branch_id, staffbase_user_id);

-- After backfill, make the column not-null so future inserts must specify
-- it. (Skipped if any row is still null — which happens only when there
-- are zero registered tenants. In that case the column stays nullable and
-- the app layer is responsible for rejecting login attempts without a
-- branch.)
do $$
begin
  if not exists (select 1 from users where staffbase_branch_id is null) then
    alter table users alter column staffbase_branch_id set not null;
  end if;
end $$;
